### PR TITLE
En translate

### PR DESCRIPTION
**Pull request by Arefyekkalam**

### CODE REVIEW

**Comment by Arefyekkalam** [comment]
merge en-translate branch

**Comment by Arefyekkalam** [comment]
merge

**Comment by blackholll** [comment]
Thank you very much for you pr.  If it is all in English, it may not be very friendly to domestic users. A more reasonable way should be to use Chinese and English for the readme, and then other files support internationalization (it may take some time to wait until later). can you pr a readme_en.md

**Comment by blackholll** [comment]
@Arefyekkalam admin site in loonflow is removed since r0.3 . 
from r0.3 workflow manage frontend page is provided. so it's no need to install admin

**Comment by blackholll** [comment]
added to https://github.com/blackholll/loonflow/blob/master/README_en.md ,   thanks for you translate

**Pull request closed without merging**
